// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:39a11b8c-004c-44f3-bd6b-b1945abfde11",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_i4qcP3xlj",
    "aws_user_pools_web_client_id": "3kga9nhbhof15jkeuaaombm75d",
    "oauth": {}
};


export default awsmobile;
